sudo: required
dist: xenial
language: cpp

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-xenial
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt510base
  - sudo apt-get install -qq qt510tools qt510script qt510webengine qt510webchannel

script:
  - source /opt/qt510/bin/qt510-env.sh
  - mkdir _build
  - cd _build
  - qmake ..
  - make -j 4

notifications:
  email: false
